spring.application.name=business-erp-core

spring.datasource.url=jdbc:mysql://localhost:3306/business_erp_dev?serverTimezone=UTC

spring.datasource.username=root

spring.datasource.password=rohit@123

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

server.port=8080